config/routes.rb
Rails.application.routes.draw do
  resources :books

  root to: "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController   
    def index
        @books = Book.all
    end
    

    def show
        @book = Book.find(params[:id])
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        if 
            @book.update(book_params)
            redirect_to books_path, notice: "更新成功"
        else
            render :edit
        end
        
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        if 
            @book.save
            redirect_to books_path, notice: "新增成功"
        else
            render :new
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path, notice: "刪除成功"
    end

    private
    def book_params
        params.require(:book).permit(:name, :date, :price, :pages, :ISBN)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<h1>編輯書籍</h1>

<%= form_with(model:@book) do |form| %>
    <div>      
        <%= form.label :name, "書名" %>
        <%= form.text_field :name %>
    </div>
    <div>      
        <%= form.label :date, "出版日期" %>
        <%= form.date_field :date, max: Date.today %>
    </div>
    <div>      
        <%= form.label :price, "售價" %>
        <%= form.number_field :price, min: 1 %>
    </div>
    <div>      
        <%= form.label :pages, "頁數" %>
        <%= form.number_field :pages, min: 1 %>
    </div>
    <div>      
        <%= form.label :ISBN, "ISBN" %>
        <%= form.text_field :ISBN %>
    </div>
    <%= form.submit %>
<% end %>

app/views/books/index.html.erb
<h1>書列表</h1>

<%= link_to '新增書籍', new_book_path %>


<% @books.each do |book| %>
  <li>
    <%= link_to book.name, book_path(book) %>
    |
    <%= link_to '刪除', book_path(book), method: "delete",data:{
        confirm: "確定要刪除嗎"
    } %>
  </li>
<% end %>

app/views/books/new.html.erb
<h1>新增書籍</h1>

<%= form_with(model:@book) do |form| %>
    <div>      
        <%= form.label :name, "書名" %>
        <%= form.text_field :name %>
    </div>
    <div>      
        <%= form.label :date, "出版日期" %>
        <%= form.date_field :date, max: Date.today %>
    </div>
    <div>      
        <%= form.label :price, "售價" %>
        <%= form.number_field :price, min: 1 %>
    </div>
    <div>      
        <%= form.label :pages, "頁數" %>
        <%= form.number_field :pages, min: 1 %>
    </div>
    <div>      
        <%= form.label :ISBN, "ISBN" %>
        <%= form.text_field :ISBN %>
    </div>
    <%= form.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>

<li>書名:<%= @book.name %></li>
<li>出版日期:<%= @book.date %></li>
<li>售價：<%= @book.price %></li>
<li>頁數:<%= @book.pages %></li>
<li>ISBN:<%= @book.ISBN %></li>

<%= link_to '編輯', edit_book_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>